"""empty message

Revision ID: 75acdad81a5e
Revises: e4705190176b
Create Date: 2024-06-27 17:08:12.976164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75acdad81a5e'
down_revision: Union[str, None] = 'e4705190176b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('testtable', 'worker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('types_examples', 'date_val',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("TIMEZONE('utc',now())"),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('types_examples', 'date_val',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('testtable', 'worker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
