"""empty message

Revision ID: b24a59dc42b3
Revises: 
Create Date: 2024-06-27 16:43:43.736690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b24a59dc42b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anothertesttable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('another_title', sa.String(length=256), nullable=False),
    sa.Column('another_compensation', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tablename',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_col', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testtable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('compensation', sa.Integer(), nullable=False),
    sa.Column('workload', sa.Enum('fulltime', 'parttime', name='workload'), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['tablename.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('limit_val', sa.String(length=50), nullable=True),
    sa.Column('maybe_none_val', sa.String(length=256), nullable=True),
    sa.Column('enum_val', sa.Enum('1', '2', name='_exampleenumdecl'), nullable=False),
    sa.Column('foreign_val', sa.Integer(), nullable=True),
    sa.Column('date_val', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['foreign_val'], ['tablename.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('linkingtable',
    sa.Column('testtable_link', sa.Integer(), nullable=False),
    sa.Column('anothertesttable_link', sa.Integer(), nullable=False),
    sa.Column('simple_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['anothertesttable_link'], ['anothertesttable.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['testtable_link'], ['testtable.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('testtable_link', 'anothertesttable_link')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linkingtable')
    op.drop_table('types_examples')
    op.drop_table('testtable')
    op.drop_table('tablename')
    op.drop_table('anothertesttable')
    # ### end Alembic commands ###
